### ISSUE TITLE
A guest checkout with Klarna: «There has been an error with your address» / «Please check the following fields: First name, Last name»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [p-pcs/core#5]
![02](https://user-images.githubusercontent.com/83204/65606962-943fa700-dfcd-11e9-9058-1d1610389fe8.png)

![03](https://user-images.githubusercontent.com/83204/65607091-c4874580-dfcd-11e9-83ed-66073e654169.png)

![04](https://user-images.githubusercontent.com/83204/65607486-758de000-dfce-11e9-9831-26041b88ae6c.png)

**Comment by dmitry-fedyuk** [comment]
Fixed in [0.0.4](https://github.com/p-pcs/core/releases/tag/0.0.4).

**Comment by dmitrii-fediuk** [comment]
Fixed in [0.0.4](https://github.com/p-pcs/core/releases/tag/0.0.4).
